-- =============================================
-- Voglio — Full Database Migration
-- Run this in the Supabase SQL Editor of your new project
-- =============================================

-- 1. TABLES

CREATE TABLE IF NOT EXISTS public.category (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    name VARCHAR NOT NULL,
    description TEXT,
    is_private BOOLEAN DEFAULT false NOT NULL,
    user_id UUID DEFAULT auth.uid(),
    emoji_code VARCHAR,
    CONSTRAINT category_pkey PRIMARY KEY (id)
);

ALTER TABLE public.category OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.size (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    value VARCHAR NOT NULL,
    CONSTRAINT size_pkey PRIMARY KEY (id)
);

ALTER TABLE public.size OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.voglio (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    name VARCHAR,
    notes TEXT,
    category_id BIGINT,
    reference_link VARCHAR DEFAULT ''::VARCHAR,
    size_id BIGINT,
    image_url VARCHAR,
    user_id UUID DEFAULT auth.uid() NOT NULL,
    quantity BIGINT DEFAULT '0'::BIGINT NOT NULL,
    CONSTRAINT voglio_pkey PRIMARY KEY (id),
    CONSTRAINT voglio_category_id_fkey FOREIGN KEY (category_id)
        REFERENCES public.category(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT voglio_size_id_fkey FOREIGN KEY (size_id)
        REFERENCES public.size(id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE public.voglio OWNER TO postgres;

-- 2. ROW LEVEL SECURITY

ALTER TABLE public.category ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.size ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voglio ENABLE ROW LEVEL SECURITY;

-- Category policies
CREATE POLICY "Enable insert for authenticated users only" ON public.category
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable users to view their own data only" ON public.category
    FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Voglio policies
CREATE POLICY "Enable delete for users based on user_id" ON public.voglio
    FOR DELETE USING ((( SELECT auth.uid() AS uid) = user_id));

CREATE POLICY "Enable insert for authenticated users only" ON public.voglio
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable insert for users based on user_id" ON public.voglio
    FOR INSERT WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));

CREATE POLICY "Enable users to view their own data only" ON public.voglio
    FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

CREATE POLICY "Policy with authenticated user only" ON public.voglio
    FOR UPDATE USING ((( SELECT auth.uid() AS uid) = user_id));

-- Size policies (read-only for all authenticated users)
CREATE POLICY "Enable read access for all users" ON public.size
    FOR SELECT USING (true);

-- 3. SEED DATA (sizes lookup table)

INSERT INTO public.size (id, created_at, value) VALUES
    (1, '2025-02-04 22:44:40.650783+00', 'XS'),
    (2, '2025-02-04 22:44:49.324918+00', 'S'),
    (3, '2025-02-04 22:44:56.207069+00', 'M'),
    (4, '2025-02-04 22:45:19.474943+00', 'L'),
    (5, '2025-02-04 22:45:30.18778+00', 'XL')
ON CONFLICT (id) DO NOTHING;

-- Restart sequences to avoid conflicts
SELECT setval('public.size_id_seq', (SELECT max(id) FROM public.size));

-- 4. STORAGE BUCKET

-- Create the bucket (run this or create via Dashboard > Storage > New bucket)
INSERT INTO storage.buckets (id, name, public) VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS: users can only access their own folder
CREATE POLICY "Give users access to own folder 1ffg0oo_0" ON storage.objects
    FOR INSERT WITH CHECK (
        (bucket_id = 'images'::text)
        AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])
    );

CREATE POLICY "Give users access to own folder 1ffg0oo_1" ON storage.objects
    FOR SELECT USING (
        (bucket_id = 'images'::text)
        AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])
    );
