-- =============================================
-- Voglio — Full Database Migration
-- Run this in the Supabase SQL Editor of your new project
-- =============================================

-- 1. TABLES

CREATE TABLE IF NOT EXISTS public.category (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    name VARCHAR NOT NULL,
    description TEXT,
    is_private BOOLEAN DEFAULT false NOT NULL,
    user_id UUID DEFAULT auth.uid(),
    emoji_code VARCHAR,
    CONSTRAINT category_pkey PRIMARY KEY (id)
);

ALTER TABLE public.category OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.size (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    value VARCHAR NOT NULL,
    CONSTRAINT size_pkey PRIMARY KEY (id)
);

ALTER TABLE public.size OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.voglio (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    name VARCHAR,
    notes TEXT,
    category_id BIGINT,
    reference_link VARCHAR DEFAULT ''::VARCHAR,
    size_id BIGINT,
    image_url VARCHAR,
    user_id UUID DEFAULT auth.uid() NOT NULL,
    quantity BIGINT DEFAULT '0'::BIGINT NOT NULL,
    price NUMERIC,
    CONSTRAINT voglio_pkey PRIMARY KEY (id),
    CONSTRAINT voglio_category_id_fkey FOREIGN KEY (category_id)
        REFERENCES public.category(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT voglio_size_id_fkey FOREIGN KEY (size_id)
        REFERENCES public.size(id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE public.voglio OWNER TO postgres;

-- Profiles table (one row per auth user)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT UNIQUE NOT NULL,
    display_name TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE public.profiles OWNER TO postgres;

-- Profile extra fields
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS shirt_size TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS pants_size TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS shoe_size TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS favorite_color TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS favorite_food TEXT;

-- Follows table
CREATE TABLE IF NOT EXISTS public.follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    following_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    UNIQUE(follower_id, following_id)
);

ALTER TABLE public.follows OWNER TO postgres;

-- Add missing columns to voglio
ALTER TABLE public.voglio ADD COLUMN IF NOT EXISTS is_private BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE public.voglio ADD COLUMN IF NOT EXISTS price NUMERIC;
ALTER TABLE public.voglio ADD COLUMN IF NOT EXISTS is_taken BOOLEAN DEFAULT false NOT NULL;

-- 2. ROW LEVEL SECURITY

ALTER TABLE public.category ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.size ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voglio ENABLE ROW LEVEL SECURITY;

-- Category policies
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.category;
CREATE POLICY "Enable insert for authenticated users only" ON public.category
    FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Enable users to view their own data only" ON public.category;
CREATE POLICY "Categories are viewable by all authenticated users" ON public.category
    FOR SELECT TO authenticated USING (is_private = false OR auth.uid() = user_id);

DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON public.category;
CREATE POLICY "Enable delete for users based on user_id" ON public.category
    FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Enable update for users based on user_id" ON public.category;
CREATE POLICY "Enable update for users based on user_id" ON public.category
    FOR UPDATE USING (auth.uid() = user_id);

-- Voglio policies
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON public.voglio;
CREATE POLICY "Enable delete for users based on user_id" ON public.voglio
    FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.voglio;
DROP POLICY IF EXISTS "Enable insert for users based on user_id" ON public.voglio;
CREATE POLICY "Enable insert for authenticated users only" ON public.voglio
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable insert for users based on user_id" ON public.voglio
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Enable users to view their own data only" ON public.voglio;
CREATE POLICY "Voglios are viewable by all authenticated users" ON public.voglio
    FOR SELECT TO authenticated USING (is_private = false OR auth.uid() = user_id);

DROP POLICY IF EXISTS "Policy with authenticated user only" ON public.voglio;
CREATE POLICY "Voglios can be updated by any authenticated user" ON public.voglio
    FOR UPDATE TO authenticated USING (true);

-- Size policies (read-only for all authenticated users)
CREATE POLICY "Enable read access for all users" ON public.size
    FOR SELECT USING (true);

-- Profiles RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Profiles are viewable by all authenticated users" ON public.profiles
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can create their own profile" ON public.profiles
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON public.profiles
    FOR UPDATE TO authenticated USING (auth.uid() = id);

-- Follows RLS
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Follows are viewable by all authenticated users" ON public.follows
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can follow others" ON public.follows
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = follower_id);

CREATE POLICY "Users can unfollow" ON public.follows
    FOR DELETE TO authenticated USING (auth.uid() = follower_id);

-- Voglio taken table (which voglios have been claimed by which users)
CREATE TABLE IF NOT EXISTS public.voglio_taken (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voglio_id BIGINT NOT NULL REFERENCES public.voglio(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    UNIQUE(voglio_id, user_id)
);

ALTER TABLE public.voglio_taken OWNER TO postgres;

ALTER TABLE public.voglio_taken ENABLE ROW LEVEL SECURITY;

CREATE POLICY "voglio_taken are viewable by all authenticated users" ON public.voglio_taken
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can mark voglio as taken" ON public.voglio_taken
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can unmark voglio as taken" ON public.voglio_taken
    FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 3. SEED DATA (sizes lookup table)

INSERT INTO public.size (id, created_at, value) VALUES
    (1, '2025-02-04 22:44:40.650783+00', 'XS'),
    (2, '2025-02-04 22:44:49.324918+00', 'S'),
    (3, '2025-02-04 22:44:56.207069+00', 'M'),
    (4, '2025-02-04 22:45:19.474943+00', 'L'),
    (5, '2025-02-04 22:45:30.18778+00', 'XL')
ON CONFLICT (id) DO NOTHING;

-- Restart sequences to avoid conflicts
SELECT setval('public.size_id_seq', (SELECT max(id) FROM public.size));

-- 4. STORAGE BUCKET

-- Create the bucket (run this or create via Dashboard > Storage > New bucket)
INSERT INTO storage.buckets (id, name, public) VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS: users can read any image but only write to their own folder
DROP POLICY IF EXISTS "Give users access to own folder 1ffg0oo_0" ON storage.objects;
DROP POLICY IF EXISTS "Give users access to own folder 1ffg0oo_1" ON storage.objects;

CREATE POLICY "Give users access to own folder 1ffg0oo_0" ON storage.objects
    FOR INSERT WITH CHECK (
        (bucket_id = 'images'::text)
        AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])
    );

CREATE POLICY "Images are readable by all authenticated users" ON storage.objects
    FOR SELECT USING (
        bucket_id = 'images'::text
    );
